### ISSUE TITLE
missing class PDO

### ISSUE THREAD

**Issue by tatamu-fold** [simplesamlphp/simplesamlphp-module-sqlauth#3]
Hello, when I tried to use this module with simplesamlphp, I got an error telling me class `PDO` on line 101 of https://github.com/simplesamlphp/simplesamlphp-module-sqlauth/blob/master/lib/Auth/Source/SQL.php cannot be found, while adding a `\` before `PDO` will make it work. I noticed the `\` was removed in commit https://github.com/simplesamlphp/simplesamlphp-module-sqlauth/commit/ca150ea786c13c2027df7fdefaa7d115c755cf8d, not sure if  `use PDO;` in line 6 functions as expected.

I'm not that familiar with PHP, so please let me know if I missed something. Thanks!

**Comment by tvdijen** [comment]
That's very strange.. What version of PHP are you using? And what version of SimpleSAMLphp and of the module?

**Comment by tatamu-fold** [comment]
@tvdijen Thanks for your quick reply. I'm using it inside a docker containter:

```
FROM php:7.4-apache
RUN apt update && apt install wget default-mysql-client -y
RUN docker-php-ext-install mysqli pdo_mysql
RUN a2enmod ssl

(Then I download 1.19.1 from GitHub and extract it)
````

**Comment by tvdijen** [comment]
Ah, that's unfortunate.. Can't reproduce that myself..

**Comment by tatamu-fold** [comment]
I've tried natively with Ubuntu 20.04 and PHP 7.4 as well, same for the need to add `\`

**Comment by tvdijen** [comment]
My guess is that the tarball was created on a system that doesn't have the pdo-extension installed and therefore the autoload-cache has no reference to the class

**Comment by tatamu-fold** [comment]
You mean https://github.com/simplesamlphp/simplesamlphp/releases/download/v1.19.1/simplesamlphp-1.19.1.tar.gz this file?

**Comment by tvdijen** [comment]
Yes, that's the one you're using right?

**Comment by tatamu-fold** [comment]
Yes

**Comment by tatamu-fold** [comment]
But how come there's cache in the tarball?

**Comment by tvdijen** [comment]
Because it's a pre-build package... That's just how composer works..

**Comment by tatamu-fold** [comment]
> I've tried natively with Ubuntu 20.04 and PHP 7.4 as well, same for the need to add `\`

I forgot to mention this one I installed from the source code, following https://simplesamlphp.org/docs/stable/simplesamlphp-install-repo

**Comment by tvdijen** [comment]
Ah, that kinda rules out what I was thinking..

**Comment by tvdijen** [comment]
I've tried several things, but I can't reproduce this at all.. :(

**Comment by tatamu-fold** [comment]
logs for your reference:

```
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] Backtrace:
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] 1 /var/simplesamlphp/www/_include.php:20 (SimpleSAML_exception_handler)
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] 0 [builtin] (N/A)
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] Caused by: Error: Class 'SimpleSAML\Module\sqlauth\Auth\Source\PDO' not found
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] Backtrace:
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] 5 /var/simplesamlphp/modules/sqlauth/lib/Auth/Source/SQL.php:90 (SimpleSAML\Module\sqlauth\Auth\Source\SQL::connect)
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] 4 /var/simplesamlphp/modules/sqlauth/lib/Auth/Source/SQL.php:138 (SimpleSAML\Module\sqlauth\Auth\Source\SQL::login)
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] 3 /var/simplesamlphp/modules/core/lib/Auth/UserPassBase.php:318 (SimpleSAML\Module\core\Auth\UserPassBase::handleLogin)
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] 2 /var/simplesamlphp/modules/core/www/loginuserpass.php:84 (require)
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] 1 /var/simplesamlphp/lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] 0 /var/simplesamlphp/www/module.php:10 (N/A)
May 14 09:22:47 simplesamlphp ERROR [a65cd80e49] Error report with id e876f650 generated.
```

**Comment by tvdijen** [comment]
I wasn't doubting you ;)  Maybe it's a Debian-thing.. I remember on some differences when it comes to php extensions.
Could you login as admin, click 'Information on your PHP-installation' and compare with mine?

![afbeelding](https://user-images.githubusercontent.com/841045/118242840-07957580-b49e-11eb-8267-723313eaf48a.png)

![afbeelding](https://user-images.githubusercontent.com/841045/118242929-272c9e00-b49e-11eb-869d-500479d9f646.png)

![afbeelding](https://user-images.githubusercontent.com/841045/118243026-43c8d600-b49e-11eb-8ead-b4357dd38ae0.png)

![afbeelding](https://user-images.githubusercontent.com/841045/118242636-d74dd700-b49d-11eb-994e-014425757af9.png)

**Comment by tvdijen** [comment]
Never mind, I feel very very stupid now....   This bug was already fixed, just not released yet.
Your version is missing the use-statements necessary (I could tell by the line-numbers in your stack trace).

So, the solution is to either manually fix it, run a composer update to pull in the latest version of the module, or to wait for v1.19.2 to be released..

**Comment by tatamu-fold** [comment]
Thanks for your reply. Sorry for not providing the logs at the beginning as it may facilitate debugging. Actually, I noticed https://simplesamlphp.org/docs/1.19/simplesamlphp-changelog#:~:text=Fixed%20a%20bug%20that%20rendered%20the%20module%20useless%20due%20to%20missing%20use-statements days ago, but I failed to realize that this is the module I'm using. Glad to see that it's already fixed via https://github.com/simplesamlphp/simplesamlphp/commit/52ce9d081b9f594f384b531df109d747a31b0d1e and https://github.com/simplesamlphp/simplesamlphp-module-sqlauth/commit/c2dc4fc8aa6d8b2408131e09b39f06d8610ff374
If I could have looked into the 1.0 branches, I should have solved the problems myself.

I noticed that now in https://github.com/simplesamlphp/simplesamlphp/blob/master/composer.lock simplesamlphp-module-sqlauth is not included, does it mean it will be removed in ssp 2.0? BTW, do you have a schedule of when will ssp 2.0 be released? 

Again, thanks for your time!

**Comment by tvdijen** [comment]
The idea is to keep the main release as clean as possible and have people install the modules they need using composer.
Also the main goal for 2.0 is to have proper integration with the Symfony framework and possibly a new version of our saml2-library, so I wouldn't expect this to be released any time soon.
We may get some extra resources during the year though, so who knows!  There's no fixed schedule anyway..

**Comment by tatamu-fold** [comment]
I see. Indeed good idea to keep main repo clean, and composer install isn't that hard :) Thanks for your answer!

**Comment by buckbeak99** [comment]
```bash
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION  

Backtrace:  
1 www/_include.php:17 (SimpleSAML_exception_handler)  
0 [builtin] (N/A)  
Caused by: Exception: The module 'sqlauth' is not enabled.  
Backtrace:  
7 lib/SimpleSAML/Module.php:444 (SimpleSAML\Module::resolveClass)  
6 lib/SimpleSAML/Auth/Source.php:335 (SimpleSAML\Auth\Source::parseAuthSource)  
5 lib/SimpleSAML/Auth/Source.php:381 (SimpleSAML\Auth\Source::getById)  
4 lib/SimpleSAML/Auth/Simple.php:68 (SimpleSAML\Auth\Simple::getAuthSource)  
3 lib/SimpleSAML/Auth/Simple.php:168 (SimpleSAML\Auth\Simple::login)  
2 modules/core/www/authenticate.php:38 (require)  
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)  
0 www/module.php:10 (N/A)
```
I got this error. Please help me to solve this issue.
Thanks in Advance

**Comment by buckbeak99** [comment]
go to your config.php and enable the module.
```bash
<?php
$config = [
  module.enable = [
    'core' => null,
    'saml' => true,
    'customAuth' => true,
    'sqlauth' => true,

  ],
],
```
