### ISSUE TITLE
saml/sp instead of sqlauth/SQL

### ISSUE THREAD

**Issue by nichierichetti** [simplesamlphp/simplesamlphp-module-sqlauth#5]
Hello there,

I am trying to create the IdP and SP to use my existing SQL database (sqlauth) as source for the IdP and then a service on my website as a SP.

Despite this, I get this error:
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SimpleSAML\Error\Exception: Invalid type of authentication source 'Openstudio-Saml'. Was 'SimpleSAML\\Module\\sqlauth\\Auth\\Source\\SQL', should be '\\SimpleSAML\\Module\\saml\\Auth\\Source\\SP'.
Backtrace:
3 lib/SimpleSAML/Auth/Source.php:388 (SimpleSAML\Auth\Source::getById)
2 modules/saml/www/sp/saml2-acs.php:14 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)
```

The problem must come from the fact  that It redirects me to .../simplesaml/www/module.php/saml/sp/saml2-acs.php/Openstudio-Saml where it uses saml as SP, while I need to use sqlauth for SQL

Can someone give me a clue on how to fix this?
Thanks in advance

**Comment by thijskh** [comment]
Probably this is just a configuration error then. Can you show your authsources config please?
